### ISSUE TITLE
RFE: Allow explicit selection of Mero storage tier in PyClovis and sage backend

### ISSUE THREAD

**Issue by ijjorama** [DiamondLightSource/DosNa#13]
Currently, PyClovis uses the default pool fid for selecting a storage tier by passing NULL at https://github.com/DiamondLightSource/DosNa/blob/master/dosna/support/pyclovis/clovis_functions.c#L207.

It would be more flexible to allow the caller to specify a storage tier, because one cannot rely on the default tier on multi-pool client nodes (e.g. the Tier-2/Tier-3 nodes in the SAGE prototype cluster) being the desired tier. 

A convenient approach for the user to specify a tier would be to supply a parameter such as "nvdimm"/"ssd"/"hdd" to identify the desired storage tier (and have some lookup of the corresponding f_container and f_key values). However, an intermediate step would be to allow direct specification of these values.

**Comment by EmilioPeJu** [comment]
Hi @ijjorama ,  thanks for the suggestion.
 I have implemented this in commit: https://github.com/DiamondLightSource/DosNa/commit/0f4f66d3f14ebf1ab969d288ad15029aca67d9de
It's implemented as an array of struct pointers, and the configuration file only requires a parameter called "tier" with the index to the right pointer (e.g: tier=2 would use Tier-2 and so on).
Feel free to create a pull request to add a new tier configuration, if you need it.

Regards, Emilio

**Comment by EmilioPeJu** [comment]
I believe that f_key changes frequently, maybe we should have that as a pyclovis parameter instead ( or set them when we are sure that they are not going to change it)
