### ISSUE TITLE
Fix formatting of Elapsed time in 

### ISSUE THREAD

**Issue by ijjorama** [DiamondLightSource/DosNa#6]
Hi,
Running examples/sequential_convolution.py, elapsed times aren't reported correctly:
...

```
Starting Test == Backend: s3, Engine: cpu, config: {'verify': '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem', 'name': 'ignored', 'endpoint_url': 'https://ceph-res-gw1.fds.rl.ac.uk'}, Out: .
Loading Data -- shape: 64 chunk_size: 32
[*] %s -- Elapsed: %.4f seconds
Convolving in 3D
[*] %s -- Elapsed: %.4f seconds
```

This would appear to arise from the line https://github.com/DiamondLightSource/DosNa/blob/5fdfd1df207bea10ada8cd24f0529aa7b99699b5/dosna/util/__init__.py#L40 

I've got a fix for this locally (reverted to using old-fashion '%' interpolation for formatting), which now prints output like:

```
Loading Data -- shape: 64 chunk_size: 32
[*] Data loaded -- Elapsed: 1.9998 seconds
Convolving in 3D
[*] Separable 3D convolution -- Elapsed: 1.4059 seconds
Convolving axis Z
Convolving axis Y
Convolving axis X
[*] Three separable 1D convolutions -- Elapsed: 5.9136 seconds
```

What's the best way for me to submit this bug fix for consideration?

Thanks,
Ian.

**Comment by EmilioPeJu** [comment]
Thank you for detecting this bug,
it's already fixed, but using the new format style instead:
 `print('[*] {} -- Elapsed: {:.4f} seconds'.format(self.name, self.time))`

Next time you have a bug fix, please commit it to your fork, that way I will be able to merge (or pick the commit that solves it)

**Comment by ijjorama** [comment]
Fixed in master.
